# Generated by Django 3.0.5 on 2020-07-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('youtube_id', models.CharField(max_length=128, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='videosyncpodcast',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videosyncpodcast',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videosync.YouTubeAccount'),
        ),
    ]
