# Generated by Django 3.0.5 on 2020-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0003_auto_20200705_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosyncepisode',
            name='upload_status',
            field=models.CharField(blank=True, choices=[('P', 'In Progress'), ('S', 'Success'), ('F', 'Failed')], max_length=1, null=True),
        ),
    ]
