# Generated by Django 3.0.5 on 2020-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0004_videosyncepisode_upload_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosyncepisode',
            old_name='youtube_url',
            new_name='youtube_id',
        ),
    ]
