# Generated by Django 3.0.5 on 2020-07-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0005_auto_20200707_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosyncepisode',
            name='preview_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
