# Generated by Django 3.0.5 on 2020-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0008_add_hex_to_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosyncepisode',
            name='audio_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
