# Generated by Django 3.0.5 on 2020-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0009_videosyncepisode_audio_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosyncpodcast',
            name='blur_image_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
