# Generated by Django 3.0.5 on 2020-07-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0010_videosyncpodcast_blur_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosyncepisode',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
