# Generated by Django 3.0.5 on 2020-07-25 17:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0011_auto_20200720_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosyncepisode',
            name='sync_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
